language: c

sudo: false

addons:
  apt_packages:
   - pkg-config
   - libdbus-1-dev
   - libcap-ng-dev

before_script:
 - ./bootstrap.py
 - ./waf configure

script:
 - ./waf build

notifications:
  recipient:
   - alessandro@ghedini.me
  email:
    on_success: change
    on_failure: always
