language: c

before_script:
 - ./bootstrap.py
 - ./waf configure

script:
 - ./waf build

notifications:
  recipient:
   - alessandro@ghedini.me
  email:
    on_success: change
    on_failure: always
